name: xsd-gen
version: '0.2.4' 
summary: Tool to generate XSD from XML.
description: |
  Tool tries to infer schema from XML file, and generates corresponding XSD.

confinement: devmode

apps:
  xsd-gen:
    command: java -jar $SNAP/xsd-gen-0.2.4/xsd-gen-0.2.4.jar

parts:
  xsd-gen:
    plugin: gradle
    source: .
    build: |
      export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
      ./gradlew fatJar
    install: |
      cp build/libs/xsd-gen-0.2.4.jar $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - openjdk-8-jdk